#!/usr/bin/env ruby
require_relative 'aws'

name = ARGV[0]
region = ARGV[1] || 'us-east-1'

instance = Aws::EC2::Resource.ttd_instance(name, region)
warn Time.now
instance.start_instance
warn "\n\nwaiting until running ..."
instance.wait_until_running(delay: 120)
