#!/bin/sh
cd ~/code/chef/cookbooks
for cookbook in `\ls`; do
  echo $cookbook
  cd ~/code/chef/cookbooks/${cookbook}
  for vm in `kitchen list | grep -v 'Not Created' | grep ChefZero | awk '{print $1}'`; do
    echo "  destroy $vm"
    kitchen destroy $vm
  done
done
