#!/bin/sh
# cd ~/code/chef/cookbooks; for i in `\ls`; do cd ~/code/chef/cookbooks/${i} && kitchen destroy & done
cd ~/code/chef/cookbooks; for i in `\ls`; do cd ~/code/chef/cookbooks/${i} && kitchen destroy done

