#!/bin/bash
# Usage: clorepl [nrepl-port] [imagename]
#        nrepl-port: default is 7100
#        imagename: default is the current directory's name

source cloprep

# try to delete the .nrepl-port file.
# the docker container user may not be able to delete it  owned by the host user
# rm -f .nrepl-port
# rm -f .lein-env

if [[ -z $NUM_ARG ]]; then
    NREPL_PORT=7100
else
    NREPL_PORT=$NUM_ARG
fi

docker run \
  -ti \
  --rm \
  --workdir $DOCKER_WORKDIR \
  --add-host mysql.dev:10.10.0.110 \
  --add-host mysql.prod:10.5.0.138 \
  -p 127.0.0.1:$NREPL_PORT:7100 \
  -v $CURR_PATH:$DOCKER_WORKDIR \
  -v $CURR_PATH/.docker-state/m2:$DOCKER_USER_HOME/.m2 \
  -v $CURR_PATH/.docker-state/lein:$DOCKER_USER_HOME/.lein \
  -v $CURR_PATH/.docker-state/log:$DOCKER_WORKDIR/log \
  -v $CURR_PATH/../.. \
  $PROJ_NAME \
  /bin/bash
