#!/bin/bash
# Usage: clorepl [nrepl-port] [imagename]
#        nrepl-port: default is 7100
#        imagename: default is the current directory's name

ARG_COUNT=$#
ARGS=$@
source cloprep

if [[ -z $NUM_ARG ]]; then
  NREPL_PORT=7100
else
  NREPL_PORT=$NUM_ARG
fi

if [[ $ARG_COUNT -ne 0 ]]; then
  CMD=$ARGS
else
  CMD=/bin/bash
fi

docker run \
  -ti \
  --rm \
  --workdir $DOCKER_WORKDIR \
  -v $CURR_PATH:$DOCKER_WORKDIR \
  $CLO_VOLUMES \
  $DOCKER_RUN_FLAGS \
  $PROJ_NAME \
  $CMD
