#!/bin/bash
# Usage: clobuild [imagename]
#        imagename: default is the current directory's name

source cloprep

cp $SCRIPT_DIR/clodockerfile .docker-state/Dockerfile

if [[ -f bin/pre-build ]]; then
  source bin/pre-build
fi

docker build --build-arg USERID=$USERID --build-arg USERNAME=$WHOAMI -f .docker-state/Dockerfile -t "$PROJ_NAME" .

if [[ -f bin/post-build ]]; then
  source bin/post-build
fi

if [[ -f bin/user-build ]]; then
  clobash bin/user-build
fi

echo
echo "Built image: $PROJ_NAME"

