#!/bin/bash
# Usage: clorepl [nrepl-port] [imagename]
#        nrepl-port: default is 7100
#        imagename: default is the current directory's name

source cloprep

# try to delete the .nrepl-port file.
# the docker container user may not be able to delete it  owned by the host user
# rm -f .nrepl-port
# rm -f .lein-env

if [[ -z $NUM_ARG ]]; then
    NREPL_PORT=7100
else
    NREPL_PORT=$NUM_ARG
fi

docker run \
  -ti \
  --rm \
  --workdir $DOCKER_WORKDIR \
  -v $CURR_PATH:$DOCKER_WORKDIR \
  $CLO_VOLUMES \
  $DOCKER_RUN_FLAGS \
  $PROJ_NAME \
  /bin/bash
