#!/bin/bash
# Usage: clojure [args]+
# Example: clojure lein new app test
# Example: clojure lein new luminus test +cljs +swagger +auth
# Example: clojure /bin/bash


# NOTE: this image shouldn't be pushed to docker because
#       it is dependent upon the username/UID/GID of the
#       current user. This allows the files created by the
#       container to be owned by the current user.

CURRENT_VERSION=1.0.0

IMAGE_BASENAME="index.docker.io/bach/clojure-image"
IMAGE_NAME="$IMAGE_BASENAME:$CURRENT_VERSION"
NO_SIDE_EFFECTS=true
source cloprep

if [[ -d $HOME/.m2 ]]; then
    mkdir -p $HOME/.m2
    M2_VOLUME="-v $HOME/.m2:$DOCKER_USER_HOME/.m2"
fi

# ensure the correct version of clojure-image exists
if docker images | grep --quiet "$IMAGE_BASENAME.*$CURRENT_VERSION" ; then
    echo
else
    echo "building clojure-image\n"
    (cd $SCRIPT_DIR && docker build -f Dockerfile.clojure --build-arg USERNAME=$WHOAMI --build-arg USERID=$USERID -t $IMAGE_NAME .)
fi

docker run \
  -ti \
  --rm \
  --workdir $DOCKER_WORKDIR \
  -v $CURR_PATH:$DOCKER_USER_HOME/project \
  $M2_VOLUME \
  $SHARED_PORTS \
  $IMAGE_NAME \
  $@

