#!/bin/bash
# Usage: clorepl [nrepl-port] [imagename]
#        nrepl-port: default is 7100
#        imagename: default is the current directory's name

source cloprep

if [[ -z $NUM_ARG ]]; then
    NREPL_PORT=7100
else
    NREPL_PORT=$NUM_ARG
fi

docker run \
  -ti \
  --rm \
  --workdir $DOCKER_WORKDIR \
  -p 127.0.0.1:$NREPL_PORT:7100 \
  -v $CURR_PATH:$DOCKER_WORKDIR \
  $CLO_VOLUMES \
  $DOCKER_RUN_FLAGS \
  $PROJ_NAME \
  lein repl :headless :host 0.0.0.0 :port $NREPL_PORT
