#!/usr/bin/env python
# add to crontab:
# */5 * * * * . /home/bmd/.config/binfiles/.envrc; /home/bmd/.config/binfiles/dyndns >/home/bmd/Downloads/dyndns.output

import sys
import xmlrpclib
import urllib2
import os

wf_account = os.environ['WEBFACTION_USER']       # Your WebFaction Account Name
wf_password = os.environ['WEBFACTION_PW']        # Your WebFaction Control Panel Password
home_domain = os.environ['WEBFACTION_DOMAIN']    # The Domain to update (must exist in the Control Panel)

server = xmlrpclib.ServerProxy('https://api.webfaction.com/')
(session_id, account) = server.login(wf_account, wf_password)

my_ip = urllib2.urlopen('http://ip.ryansanden.com/').read().strip()

print "ip address is now: "
print my_ip

home_override = None
for override in server.list_dns_overrides(session_id):
    if override['domain'] == home_domain:
        if override['a_ip'] != '':
            home_override = override
            break

if home_override:
    print "dns is currently set to: "
    print home_override['a_ip']

if home_override and home_override['a_ip'] == my_ip:
    print "correct ip already set ..."
    sys.exit(0)

print "saving new ip address "
print my_ip

if home_override:
    server.delete_dns_override(session_id, home_domain, home_override['a_ip'])

server.create_dns_override(session_id, home_domain, my_ip)
