#!/bin/bash
#python -m SimpleHTTPServer 8080

# see rubytapas episode #255 httpd
# to find where the un library lives:
#   ruby -r un -e 'puts $LOADED_FEATURES.grep(/un.rb$/)'
ruby -run -e httpd . --port 8080
