#!/bin/sh
# docker run --rm -it \
#        -p 2181:2181 -p 3030:3030 -p 8081:8081 \
#        -p 8082:8082 -p 8083:8083 -p 9092:9092 \
#        -e ADV_HOST=192.168.1.220 \
#        landoop/fast-data-dev
docker run --rm -it \
  --net=host \
  -e ADV_HOST=192.168.86.220 \
  landoop/fast-data-dev
