#!/bin/bash
ping -c 1 $1 > /dev/null 2> /dev/null
if [[ $? -eq 0 ]]; then
  hostname=$1
else
  hostname=`ttdip $1`
fi
# echo $hostname

while true; do
  if $(nc -L 5  -G 10 -z $hostname 22); then
    break
  fi
  echo -n '.'
  sleep 2
done

echo
echo "yay, ssh is running on $1"
if [[ "$#" -gt 1 ]]; then
  shift
  sleep 5 # a little buffer just in case
  ssh "$hostname" "$@"
else
  test -x /usr/bin/say && say connected
fi

